user_input= input(pick a noun(name))
print("One sunny afternoon, " + user_input + "went on an adventure")
user_input= input(pick a place)
print("to" + user_input + ".")
user_input= input(enter the first noun)
print("In this magical place, " + user_input + "met a ")