user_input1 = input("pick a name")
user_input2 = input("pick a place")
user_input3 = input("enter the same name")
user_input35 = input("enter a plant")
user_input4 = input("enter a disney character")
user_input5 = input("enter animal number 1")
user_input6 = input("pick either his or her that goes with the name")
user_input7 = input("enter the same disney character")
user_input8 = input("enter the same name")
user_input9 = input("enter another animal, animal number 2")
user_input10 = input("enter the same name")
user_input11 = input("enter an emotion")
user_input12 = input("enter the same disney character ")
user_input13 = input("enter animal number 1")
user_input14 = input("enter a famous person")
user_input15 = input("enter the same name")
user_input16 = input("enter a physical thing in this room")
user_input17 = input("enter animal number 1")
user_input18 = input("enter the same disney character")

print("One sunny afternoon, " + user_input1 + " went on an adventure to " + user_input2 + "." + user_input3 + " needed directions to find the " + user_input35 + " to save " + user_input4 + " from the " + user_input5 + "." + " On " + user_input6 + " way to find " + user_input7 + "," + user_input8 + " finds a " + user_input9 + " and decides to follow it but it moves away too quickly. " + user_input10 + " starts to feel " + user_input11 + ", and is worried about not being able to save " + user_input12 + " from  the " + user_input13 + "." + " Thankfully, " + user_input14 + " comes out of the forest to motivate " + user_input15 + ". They use a " + user_input16 + " to kill the horrible " + user_input17 + " and successfully save " + user_input18)